// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function ClearDebugLogs() {
  return window['go']['main']['App']['ClearDebugLogs']();
}

export function DecryptDirectory(arg1, arg2) {
  return window['go']['main']['App']['DecryptDirectory'](arg1, arg2);
}

export function DecryptFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2, arg3);
}

export function EncryptDirectory(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['EncryptDirectory'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function EncryptFile(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetAvailableEncryptionMethods() {
  return window['go']['main']['App']['GetAvailableEncryptionMethods']();
}

export function GetDebugLogs() {
  return window['go']['main']['App']['GetDebugLogs']();
}

export function GetFileMetadata(arg1) {
  return window['go']['main']['App']['GetFileMetadata'](arg1);
}

export function GetHint(arg1) {
  return window['go']['main']['App']['GetHint'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function IsDirectory(arg1) {
  return window['go']['main']['App']['IsDirectory'](arg1);
}

export function LoadFileForDecryption(arg1) {
  return window['go']['main']['App']['LoadFileForDecryption'](arg1);
}

export function OnBeforeClose(arg1) {
  return window['go']['main']['App']['OnBeforeClose'](arg1);
}

export function OnDomReady(arg1) {
  return window['go']['main']['App']['OnDomReady'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function RestoreDefaultSettings() {
  return window['go']['main']['App']['RestoreDefaultSettings']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetDeleteOriginal(arg1) {
  return window['go']['main']['App']['SetDeleteOriginal'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWindowResizable(arg1) {
  return window['go']['main']['App']['SetWindowResizable'](arg1);
}

export function UpdateChannel(arg1) {
  return window['go']['main']['App']['UpdateChannel'](arg1);
}

export function UpdateChannelAndLevel(arg1, arg2) {
  return window['go']['main']['App']['UpdateChannelAndLevel'](arg1, arg2);
}

export function UpdateLevel(arg1) {
  return window['go']['main']['App']['UpdateLevel'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateFileChannel(arg1) {
  return window['go']['main']['App']['ValidateFileChannel'](arg1);
}
