// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {context} from '../models';

export function CancelOperation():Promise<void>;

export function DecryptDirectory(arg1:string,arg2:string):Promise<string>;

export function DecryptFile(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function EncryptDirectory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:boolean):Promise<string>;

export function EncryptFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:boolean):Promise<string>;

export function GetAvailableEncryptionMethods():Promise<Array<string>>;

export function GetFileMetadata(arg1:string):Promise<main.FileMetadata>;

export function GetHint(arg1:string):Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function LoadFileForDecryption(arg1:string):Promise<main.FileMetadata>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function RestoreDefaultSettings():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SetDeleteOriginal(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function UpdateChannel(arg1:number):Promise<void>;

export function UpdateChannelAndLevel(arg1:number,arg2:string):Promise<void>;

export function UpdateLevel(arg1:string):Promise<void>;

export function UpdateSettings(arg1:config.Settings):Promise<void>;

export function ValidateFileChannel(arg1:string):Promise<boolean>;
