// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptDirectory'](arg1, arg2, arg3);
}

export function DecryptFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2, arg3, arg4);
}

export function EncryptDirectory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EncryptDirectory'](arg1, arg2, arg3, arg4, arg5);
}

export function EncryptFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2, arg3, arg4, arg5);
}

export function GetFilesInDirectory(arg1) {
  return window['go']['main']['App']['GetFilesInDirectory'](arg1);
}

export function GetHint(arg1) {
  return window['go']['main']['App']['GetHint'](arg1);
}

export function IsDirectory(arg1) {
  return window['go']['main']['App']['IsDirectory'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
