// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptDirectory(arg1:string,arg2:string,arg3:number):Promise<string>;

export function DecryptFile(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<string>;

export function EncryptDirectory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function EncryptFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function GetFilesInDirectory(arg1:string):Promise<Array<string>>;

export function GetHint(arg1:string):Promise<string>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;
